
import { Shipment, Alert, Project, Supplier } from "./types";
import { addDays, subDays, format } from "date-fns";

const today = new Date();
const formatDate = (date: Date) => format(date, "yyyy-MM-dd");

export const projects: Project[] = [
  { id: "p1", name: "DXB Terminal 3 Gate Seating", customer: "Dubai Airports" },
  { id: "p2", name: "LHR T5 High-Back Rest Area", customer: "Heathrow Airport Ltd" },
  { id: "p3", name: "JFK T4 Premium Lounge Upgrade", customer: "JFKIAT" },
  { id: "p4", name: "SIN Changi Jewel Expansion", customer: "CAG" },
];

export const suppliers: Supplier[] = [
  { id: "s1", name: "SteelCraft Seating Ltd", location: "Bologna, Italy" },
  { id: "s2", name: "AeroForm Manufacturing", location: "Shenzhen, China" },
  { id: "s3", name: "Nordic Ergo Systems", location: "Oslo, Norway" },
];

export const shipments: Shipment[] = [
  {
    id: "sh1",
    reference: "AS-DXB-2024-001",
    projectId: "p1",
    projectName: "DXB Terminal 3 Gate Seating",
    customerId: "c1",
    customerName: "Dubai Airports",
    supplierId: "s1",
    supplierName: "SteelCraft Seating Ltd",
    origin: "Genoa Port, Italy",
    destination: "Jebel Ali Port, UAE",
    carrier: "Maersk",
    mode: "Sea",
    incoterms: "CIF",
    status: "In transit",
    riskLevel: "Low",
    owner: "Sarah Jenkins",
    notes: "Main batch of gate seating. 40 containers.",
    plannedShipDate: formatDate(subDays(today, 15)),
    actualShipDate: formatDate(subDays(today, 14)),
    eta: formatDate(addDays(today, 10)),
    documents: [
      { id: "d1", name: "Commercial Invoice", required: true, dueDate: formatDate(subDays(today, 12)), status: "Completed", owner: "Sarah Jenkins", type: "Financial" },
      { id: "d2", name: "Packing List", required: true, dueDate: formatDate(subDays(today, 12)), status: "Completed", owner: "Sarah Jenkins", type: "Operational" },
      { id: "d3", name: "Bill of Lading", required: true, dueDate: formatDate(subDays(today, 10)), status: "Completed", owner: "Sarah Jenkins", type: "Shipping" },
      { id: "d4", name: "Certificate of Origin", required: true, dueDate: formatDate(addDays(today, 2)), status: "Pending Review", owner: "Sarah Jenkins", type: "Customs" },
    ],
  },
  {
    id: "sh2",
    reference: "AS-LHR-2024-004",
    projectId: "p2",
    projectName: "LHR T5 High-Back Rest Area",
    customerId: "c2",
    customerName: "Heathrow Airport Ltd",
    supplierId: "s2",
    supplierName: "AeroForm Manufacturing",
    origin: "Shenzhen, China",
    destination: "London Heathrow, UK",
    carrier: "DHL Global Forwarding",
    mode: "Air",
    incoterms: "DDP",
    status: "Customs paperwork required",
    riskLevel: "High",
    owner: "Mark Thompson",
    notes: "Urgent shipment for VIP lounge reopening.",
    plannedShipDate: formatDate(subDays(today, 2)),
    actualShipDate: formatDate(subDays(today, 1)),
    eta: formatDate(addDays(today, 1)),
    documents: [
      { id: "d5", name: "Commercial Invoice", required: true, dueDate: formatDate(subDays(today, 3)), status: "Completed", owner: "Mark Thompson", type: "Financial" },
      { id: "d6", name: "Packing List", required: true, dueDate: formatDate(subDays(today, 3)), status: "Completed", owner: "Mark Thompson", type: "Operational" },
      { id: "d7", name: "Airway Bill", required: true, dueDate: formatDate(subDays(today, 1)), status: "Completed", owner: "Mark Thompson", type: "Shipping" },
      { id: "d8", name: "Customs Declaration", required: true, dueDate: formatDate(today), status: "Overdue", owner: "Mark Thompson", type: "Customs" },
    ],
  },
  {
    id: "sh3",
    reference: "AS-JFK-2024-088",
    projectId: "p3",
    projectName: "JFK T4 Premium Lounge Upgrade",
    customerId: "c3",
    customerName: "JFKIAT",
    supplierId: "s3",
    supplierName: "Nordic Ergo Systems",
    origin: "Oslo, Norway",
    destination: "JFK Port, New York",
    carrier: "Kuehne+Nagel",
    mode: "Sea",
    incoterms: "FOB",
    status: "Delayed",
    riskLevel: "Medium",
    owner: "Elena Rodriguez",
    notes: "Production delay at supplier. Port strike in Oslo.",
    plannedShipDate: formatDate(subDays(today, 10)),
    eta: formatDate(addDays(today, 30)),
    documents: [
      { id: "d9", name: "Packing List", required: true, dueDate: formatDate(subDays(today, 15)), status: "Missing", owner: "Elena Rodriguez", type: "Operational" },
    ],
  },
  {
    id: "sh4",
    reference: "AS-SIN-2024-012",
    projectId: "p4",
    projectName: "SIN Changi Jewel Expansion",
    customerId: "c4",
    customerName: "CAG",
    supplierId: "s2",
    supplierName: "AeroForm Manufacturing",
    origin: "Shenzhen, China",
    destination: "Port of Singapore",
    carrier: "SFC",
    mode: "Road",
    incoterms: "Ex-Works",
    status: "Ready for dispatch",
    riskLevel: "Low",
    owner: "Sarah Jenkins",
    notes: "Local trucking batch.",
    plannedShipDate: formatDate(addDays(today, 2)),
    eta: formatDate(addDays(today, 5)),
    documents: [
      { id: "d10", name: "Commercial Invoice", required: true, dueDate: formatDate(today), status: "Pending Review", owner: "Sarah Jenkins", type: "Financial" },
    ],
  },
];

export const alerts: Alert[] = [
  {
    id: "a1",
    shipmentId: "sh2",
    shipmentRef: "AS-LHR-2024-004",
    type: "Missing Document",
    message: "Customs Declaration is overdue for LHR shipment",
    severity: "High",
    date: formatDate(today),
  },
  {
    id: "a2",
    shipmentId: "sh3",
    shipmentRef: "AS-JFK-2024-088",
    type: "Delay",
    message: "ETA pushed back by 15 days due to Oslo port strike",
    severity: "Medium",
    date: formatDate(subDays(today, 1)),
  },
  {
    id: "a3",
    shipmentId: "sh1",
    shipmentRef: "AS-DXB-2024-001",
    type: "Urgent Action",
    message: "Packing list needs final sign-off for DXB shipment",
    severity: "Low",
    date: formatDate(today),
  },
];
